# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
disqus: missedone
google_analytics: missedone
title: missedone

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Nick's Tech Notebook

description: Nick's Tech Notebook
author:
  name: missedone
  email: missedone@gmail.com
  github: missedone
  # twitter: missedone
  pinterest: missedone@gmail.com
  linkedin: xuqing-tan
  bio: Your stylish, minimalist theme!
  email_md5: bcd7fb18d53fcd336414ad84dde8aac1

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:
  - jekyll-paginate